-- AlterTable
ALTER TABLE "App" ALTER COLUMN "bgColor" DROP NOT NULL,
ALTER COLUMN "bgColor" SET DEFAULT '#f5e3aeff',
ALTER COLUMN "primaryColor" DROP NOT NULL,
ALTER COLUMN "primaryColor" SET DEFAULT '#48e',
ALTER COLUMN "textColor" DROP NOT NULL,
ALTER COLUMN "textColor" SET DEFAULT '#000';
